### ISSUE TITLE
AlarmReceiver - FormActivity Call Sequence

### ISSUE THREAD

**Issue by safi-manar** [qtmdev/AndroidInference#5]
In `onPermissionCheckSuccess()`, `startAlarms()`is called before starting the FormActivity Intent.

Consider the case where a user opens the survey and decides not to submit the demographic information. This person's data should not be collected. Thus, the alarm should  be started upon completion of the form.

**Comment by mvc-us** [comment]
Still needs to be built, but users should be able to fill out the form at any point (in case they don't have time during app install). In this case, data should still be collected. The user has already agreed to the dialogue at this point, so we can collect data.

**Comment by safi-manar** [comment]
In the case that a user does not have time to complete -- or simply ignores-- the form, the chance that the user will find the motivation to revisit the app at a later time to fill out the form is slim. Without the form data, the data from the user's phone is useless, and that user should not be paid without fully completing the process.
As such, phone sensor data collection should occur after submission of the form.
If a user did not submit the form, we could perhaps create a daily notification that reminds the user to fill out the quick survey, or else they will not be paid.

**Comment by mvc-us** [comment]
Users don't get paid unless they fill out the form, so they definitely have an incentive to do so.

**Comment by safi-manar** [comment]
Resolved with [MainActivityClean]
